// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH_7UXHHMY8rll1RtoVPc56DD9__l8nUo',
    appId: '1:393664930642:web:b7b96a857e1d16491f908b',
    messagingSenderId: '393664930642',
    projectId: 'hospital-managemeny-system',
    authDomain: 'hospital-managemeny-system.firebaseapp.com',
    storageBucket: 'hospital-managemeny-system.firebasestorage.app',
    measurementId: 'G-YXQYKB4ZSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5LVpU8hGMPm_qLfbmharUB-K8R2I7SKk',
    appId: '1:393664930642:android:d24d1f0dc393f6801f908b',
    messagingSenderId: '393664930642',
    projectId: 'hospital-managemeny-system',
    storageBucket: 'hospital-managemeny-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuKIa8sPyxElZhLNn7AW38mz8hbSk7J80',
    appId: '1:393664930642:ios:d0c63253b228cdee1f908b',
    messagingSenderId: '393664930642',
    projectId: 'hospital-managemeny-system',
    storageBucket: 'hospital-managemeny-system.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuKIa8sPyxElZhLNn7AW38mz8hbSk7J80',
    appId: '1:393664930642:ios:d0c63253b228cdee1f908b',
    messagingSenderId: '393664930642',
    projectId: 'hospital-managemeny-system',
    storageBucket: 'hospital-managemeny-system.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH_7UXHHMY8rll1RtoVPc56DD9__l8nUo',
    appId: '1:393664930642:web:bae795b786fa4e181f908b',
    messagingSenderId: '393664930642',
    projectId: 'hospital-managemeny-system',
    authDomain: 'hospital-managemeny-system.firebaseapp.com',
    storageBucket: 'hospital-managemeny-system.firebasestorage.app',
    measurementId: 'G-T95HW7WYYZ',
  );
}
